### ISSUE TITLE
problem with float-valued TIFF

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#111]
Float-valued TIFF files (produced by certain GIS systems, see dahtah/imager/#39) aren't loaded properly. This is the case with and without the -cimg-use-tiff flag, although the outcome is different. 
I made a [gist](https://gist.github.com/dahtah/8ead764942819c5ab3dd76309d67b12c) to illustrate the issue.

**Comment by dtschump** [comment]
Hello Simon,

Commit https://github.com/dtschump/CImg/commit/374546d0d6c7446a4cfc4ca5ee8ad1e1fb6a186d seems to fix the issue.

These files appear to be double-valued tiff (64bits) instead of float-valued. I've added the code in `CImg<T>::load_tiff()` function to handle those cases.

**Comment by dahtah** [comment]
Hi David, and thanks! It seems to work with -Dcimg_use_tiff now, but not without.

**Comment by dtschump** [comment]
If you do not use `-Dcimg_use_tiff`, then the loading of the .tiff file is delegated to ImageMagick"s cli tool `convert`. I'm not really surprised it doesn't work, because only a very few tools are actually able to read such tiff images (this includes float-valued 32bits tiff as well).
The CImg support of .tiff image is actually really good as it is :)

**Comment by dahtah** [comment]
You're right, it's a failure on ImageMagick's side ("display" fails to open the file correctly). Thanks again!
