### ISSUE TITLE
bicubic sampling / warp error

### ISSUE THREAD

**Issue by cbartnl** [dtschump/CImg#150]
I probably discovered a bug somewhere in the bicubic sampling or warp function. 

The following code is ok (bilinear sampling):
```
CImg<unsigned short> testinp(500, 500, 1, 3); 
testinp = "(x * x + y * y)%200";
	
CImg<float> testxmap(500, 500, 1, 1);
testxmap = "x * 1.1";
CImg<float> testymap(500, 500, 1, 1);
testymap = "y * 1.1";
	
CImg<float> testwarpfield = testxmap.get_append(testymap, 'c');
	
CImg<unsigned short> testwarped = testinp.get_warp(testwarpfield, 0, 1);

CImgList<unsigned short> testresultlist(testinp, testwarped);
testresultlist.display();
```

With the following test image (left), and its warped counterpart (right):
![ok_bilinear_warp](https://user-images.githubusercontent.com/31511892/29928532-8cce06fe-8e69-11e7-9fe5-48d5e345a156.jpg)

But changing the code to bicubic sampling:
```
CImg<unsigned short> testwarped = testinp.get_warp(testwarpfield, 0, 2); 
```
yields the following result:
![error_bicubic_warp](https://user-images.githubusercontent.com/31511892/29928710-de6cbdfc-8e69-11e7-9606-860e1e70a7c2.jpg)

**Comment by dtschump** [comment]
I don't think this is a bug. But, this is a common mistake :)

You should not store your cubic-warped result in a `CImg<unsigned short>`, but rather in a `CImg<float>` (or eventually `CImg<short>`), because cubic interpolation does not preserve the min/max range of the original data (contrary to linear interpolation).
The result of a cubic interpolation with the kind of data you provide (with values close or equal to 0) will often generates negative values, which are unfortunately transformed as very high values when using `unsigned` pixel types (all the white pixels you see in your result).

Replacing `unsigned short` by `short` in your example solves this issue.

**Comment by dtschump** [comment]
Thinking a bit about it. 
I think this wouldn't be insane to clamp values after a cubic interpolation iff the used datatype `T` is not able to store the 'exact' value of the interpolation.
I'll prepare a patch to do this way.

**Comment by dtschump** [comment]
Patch https://github.com/dtschump/CImg/commit/bdddda159f369ac421dd3e7d5c6ac841bd206cfa should do this, and probably fix your issue as well.
Let me know.

**Comment by cbartnl** [comment]
Thanks! That is really quick! Patch seems to work!

I should have thought of the cause earlier (the lobes of the kernel do indeed become negative).
I think most other libraries do automatic clipping for unsigned types (at least I did not really notice it before), so it makes sense to patch it. Also if a user just wants to warp an image without other following operations.
