### ISSUE TITLE
How could I adjust the HSV value?

### ISSUE THREAD

**Issue by hubutui** [dtschump/CImg#165]
If I do this:
```c
CImg src("lenna.png");
CImg dest = src.get_RGBtoHSV();
// loop to adjust H, S, or V here
//
dest.save("out.png");
```
that the out.png I get is wrong. It seems that I need to convert `dest` back to RGB before I save it.

Another question is when I do the loop to change H, S, or V value, could I use those loop macro document [here](http://cimg.eu/reference/group__cimg__loops.html)? Does it assume the the RGB value range?

**Comment by StefRe** [comment]
> It seems that I need to convert dest back to RGB before I save it.

yes

>  could I use those loop macro

yes, the macros don't assume anything about the meaing of the spectrum dimensions: c is the spectrum dimension with c == 0 for R or H or whatever color channels you have

**Comment by hubutui** [comment]
I don't really understand. After `CImg dest = src.get_RGBtoHSV();`, `dest` stored HSV in an a 4th-dimensional array (width,height,depth,dim) just like RGB, H <-> R, S <-> G, B <-> V? Or is there any example code about how to use those loop macro, like `cimg_forX(img,x)`. Something like this:
```c
CImg img("lenna.png");

cimg_forX(img,x) {
// could this line means that x-plane*2?
  img(x) = img(x) * 2;
}
```

**Comment by StefRe** [comment]
Maybe it's clearer with this example:

    CImg<float> img("milla.bmp");
    img.RGBtoHSV();
    cimg_forXY(img, x, y) {
        img(x, y, 0) = std::fmod(img(x, y, 0) + 10, 360);  // shift hue
        img(x, y, 1) = std::max(1.1 * img(x, y, 1), 1.0);  // increase saturation
        img(x, y, 2) /= 1.1;                               // decrease value
    }
    img.HSVtoRGB().save("milla1.bmp");

**Comment by dtschump** [comment]
Maybe some additional hints.

- First, a `CImg<T>` instance has no clues about the meaning of the datatype it stores. It just knows the dimension of the image (width,height,depth,spectrum), but just doesn' care about what these pixel values mean. So, calling `img.RGBtoHSV()` does not activate some flag in the `CImg<T>` structure that tells : "now, my pixels are encoded with HSV".  The developer has to know what kind of pixels he deals with.

- Second, reading/writing image data from/to a file assumes you should get/send RGB values. That's why @StefRe suggests to call `HSVtoRGB()` before saving the image to a file. If you don't do that, your HSV values will be written as if they were RGB values.

This may look like a constraint, but it actually isn't. It offers a very interesting flexibility as the user can store absolutely everything he wants to a `CImg<T>`, and deals with it. He just has to remember what is the kind of data he put, which is something he obviously knows when developing a code in any way.

**Comment by hubutui** [comment]
Thanks guys. I finally get it work.

I don't really understand what depth means. Is it the bits of color channel? Is is always 1?

**Comment by dtschump** [comment]
`depth` is 1 for 2D images, but can be something else when you deal with volumetric images (more than 1 slice, e.g. MRI datasets or others). It has nothing to do with the number of bits used by the values. This is what the template type `T ` is used for.

**Comment by hubutui** [comment]
Thanks. So I think I won't have any chance to get a depth larger than 1.
