### ISSUE TITLE
Improve compilation times of CImg code

### ISSUE THREAD

**Issue by bijjuair** [dtschump/CImg#169]
Time to compile my CImg based code is taking around 2mins on a 10core machine with 64GB RAM.
I would like to know if there is any way to improve the compilation time.

1) What is the bottleneck if any that is increasing the compilation time?
2) I am using the plugins png, tiff, opencv, magick, openmp. Is the inclusion of these plugins responsible for increasing the compilation time? 
3) Is there any **easy way** to separate the CImg classes into .cpp files for faster compilation?
4) Are there any optimization flags to pass while compiling, to improve the compilation times?

**Comment by dtschump** [comment]
1. It usually depends on many different things:
   1a. The compiler you use : Usually Microsoft compilers and clang++ are slower than g++ when optimizations are turned on. Even if you use g++ : some versions of g++ are faster than others to compile a CImg-based code with optimizations. 

  1b. The complexity of your code : Usually, having a code that uses several different types of the templated classes `CImg<T>, CImgList<T>, ...` is longer to compile. I guess that is because how the compiler manages template method instantiation, but this is still not completely clear to me. Anyway, the real bottleneck IMHO is the optimization phase. Compiling a code without optimizations turned on is generally quite fast with all compilers (particularly with ̀clang++`).

2. Yes, that probably adds some complexity to the program and increase the compilation and link time, but I think this is negligible compared to the time taken by the optimization phase.

3. I really don't think separating the CImg classes into multiple files will help speeding up the compilation in any ways. To me, compilation time is mainly taken by template instantiation and optimization phases (not file parsing). This is not something we can really interact on, except if you decide to first make a library file with all pre-compiled CImg methods for the pixel type you use in your code, but in that case, you lose the advantage of having only the methods you really use to be compiled.

4. Flag `-O0` will probably help :) Apart from that, not any flags I'm aware of.

**Comment by bijjuair** [comment]
Little bit better without optimization.
Thanks.

**Comment by heckflosse** [comment]
@dtschump 

> I really don't think separating the CImg classes into multiple files will help speeding up the compilation in any ways.

Separating classes into multiple files can reduce compilation time a lot when you also define a compilation unit for each .cpp file. This way the compiler (or the make command) can use all the cores of your cpu (one core/thread per compilation unit).
Another advantage is that you don't have to compile all the stuff when you make a change to just one compilation unit. That reduces turnaround time a lot.

Example: 
one compilation unit => When building from scratch the compiler uses only one thread to compile the whole CImg

n compilation units => When building from scratch the compiler can use c threads to compile the whole CImg (c is the number you define in the make command (e.g. make -j8 for 8 cores)

Ingo

**Comment by dtschump** [comment]
> Separating classes into multiple files can reduce compilation time a lot when you also define a compilation unit for each .cpp file. This way the compiler (or the make command) can use all the cores of your cpu (one core/thread per compilation unit).

In the case of CImg, a template-based library based on a `.h` file, having several `.h` files instead of a single one wouldn't make any difference.
I agree that having several compilation units can be important, but here, this is the role of the programmer who uses the library to define these CU, not the role of the library itself.

**Comment by heckflosse** [comment]
Ok, thanks for clarification
