### ISSUE TITLE
Bad load of PNG image

### ISSUE THREAD

**Issue by VAnthony** [dtschump/CImg#218]
Hello,

I'm trying to load a png image with CImg but the image loaded doesn't correspond to the image file.
When I load the same jpg image (converted from the png image with gimp) the result is good.

This is my code : 
```
#include "CImg.h"

using namespace cimg_library;

int main() {
  CImg<unsigned char> imageJPG("image.jpg");
  CImg<unsigned char> imagePNG("image.png");

  imageJPG.resize(256, 256);
  imagePNG.resize(256, 256);

  CImgDisplay main_disp(imageJPG,"JPG"), main_disp2(imagePNG, "PNG");
  while (!main_disp.is_closed() && !main_disp2.is_closed()) {
    main_disp.wait();
    main_disp2.wait();
    }
  return 0;
}
```

I've tested this code with the last version of CImg (2.3.4) and the last version on libpng (1.6.36). 
The command line to compile this code : `g++ test.cpp -Dcimg_use_png -lpng -lz -lX11 -lpthread -ljpeg`

And here the results of this code : 

![capture d ecran de 2018-12-20 16-06-24](https://user-images.githubusercontent.com/18392930/50292208-d05b3f80-0470-11e9-97ec-22bc7f5d652b.png)

![capture d ecran de 2018-12-20 16-06-57](https://user-images.githubusercontent.com/18392930/50292241-dfda8880-0470-11e9-8980-deaaec88c513.png)

Finally the images used by my program : 

JPG : 
![marchingsquare](https://user-images.githubusercontent.com/18392930/50292303-04366500-0471-11e9-907a-3ad82b2e9aa4.jpg)

PNG : 
![marchingsquare](https://user-images.githubusercontent.com/18392930/50292304-04366500-0471-11e9-871d-ad2c1a553e1f.png)

Why my code doesn't work well with my png image ?

**Comment by VAnthony** [comment]
Thanks a lot !

Is there a way to detect the encode type of an image in order to load dynamically all type of image ?

**Comment by VAnthony** [comment]
Ok thanks again.

**Comment by sorlax2410** [comment]
Hi, can I also ask how can I load an image without cimg filling the empty space?

**Comment by matthieu-nesme** [comment]
Hi,

the issue is closed but the underlying problem remains.

Don't you think an exception should be raised when the data is cast to fit in a smaller type size? In every loaders.

For instance in the png loader, it would be great to have an exception when something like `sizeof(T)<bit_depth` (it is a bit more subtile because the signess of `T` must be considered).  
So you can react to such an exception in your calling program (e.g. raise an error or allocate an image of a different type, etc.)

Are there situations where it makes sense to overflow? In that case, at least a warning seems mandatory.
