### ISSUE TITLE
 '_fileno' was not declared in this scope

### ISSUE THREAD

**Issue by jimobama** [dtschump/CImg#43]
'_fileno' was not declared in this scope; 
At first I was though I needed to  stdio.h in other for it to work file , I try it I found is not my problem, but the library issue so decided to passed it.
I have check online if this common problem , I have notice that alot of furum have discussed about it ut none of them actual solved it. When I ignore the line of the code at 4925 in CImg.h  it compile okay.

**Comment by dtschump** [comment]
Maybe some additional info about your environement (OS, compiler, version ?) could help to make me understand what happens.
Thanks.

**Comment by dtschump** [comment]
Searching for this problem on the Internet makes clear that it is actually a bug in stdio.h that happens when the `-std=c++11` flag is enabled. There are multiple work-around, like using flag `-std=gnu++11` instead.
See : http://stackoverflow.com/questions/22081825/compiling-cimg-with-c0x-and-mingw

This is not something I can fix in the header file.
