### ISSUE TITLE
precompile math expressions

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#71]
Hi David, I'm exploring the math parser at the moment, great work! Question: how hard would it be to pre-compile expressions that are to be used repeatedly? 
Other things I've noted:
- Is it possible to grow a vector? This syntax doesn't appear to work:
  `"v = [0];v = [v,1];"`
  while this one does:
  `"v = [0];u = [v,1];"`
- Functions being actually macros makes for difficult debugging, I think. Is this very hard to fix? 
- Having map/filter/reduce and lambdas in there as well would be fantastic.

**Comment by dtschump** [comment]
Hi Simon,
The expressions are already pre-compiled into bytecodes before being interpreted, so multiple evaluations are already quite fast (even parallelized with OpenMP).
You can also force the parallelization by starting the expression with '*'.
For instance : 

    CImg<float> img(512,512);
    img.fill("*cos(x*y/10) + sin(x*y/20)",true);

- Vectors have a static size, meaning their sizes must be known at compile time, so no re-allocation of a vector with a different buffer size is possible. Also, once a variable has been declared, its type cannot be changed. In your example, `v` is a `vector3`, then you can only assign another variable of type  `vector3` to `v` (in C++, it would be a bit like trying to assign a `float[4]` to a `float[3]`).

- Custom functions are indeed macros. It has pros and cons. You can't for instance use recursive calls, but having macros is quite cool to avoid having to manage a calling stack, as well as it's also generally faster to compute (see them as `inlined` functions). So far, I didn't have needs for _real_ functions, that's why I have done it like this. I don't think it is intended to be a replacement to _Matlab_ anyway :) 

- For the last part, have you examples of what you have in mind ? I think having custom functions as macros could be helpful in this case (we could pass a function name as a macro argument for instance).

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/CImg/commit/934014657999d27f77eff4c4fda1b16f97692bed allows function names and operators to be passed as arguments of user-defined functions, like : 

    foo(op) = ((1)op(2));
    map(vec,fn) = (v=vec;for(i=0,i<size(v),++i,v[i] = fn(v[i]));v);

    x = foo(+);
    y = map([0,1,2],cos);

**Comment by devernay** [comment]
@dtschump why not propose a student project on using LLVM to make a native JIT compiler for CImg expressions: http://llvm.org/docs/tutorial/LangImpl4.html
Mesa uses this to compile GLSL shaders, and it works quite well (it can be parallelized, too)

**Comment by dtschump** [comment]
That could be funny yes !
Anyway, I must admit I haven't been already bothered by the current evaluation speed since I've got a 24-cores PC :)

**Comment by dahtah** [comment]
Thanks for your reply David. 
- Precompilation: the scenario I have in mind is one where you call im.eval(foo) for many different images im, but with the same expression "foo". As far as I understand blah would get byte-compiled every time, right? So I'm wondering if it'd be hard to have something like:
```
ByteCode foo_bc = compile(foo);
// then loop over im, im.eval(foo_bc);
```
Memoization is another way to do I guess (transparently to the user). 
- map/filter/reduce. That's the holy trinity of functional programming. g = map(f,v) applies function f to the elements of vector v, so that g_i = f(v_i). Filter:  g = filter(test,v) removes any elements of v for which test(v_i) == false. Reduce represents a map-and-accumulate operation where you apply the same operation to every element but keep a running summary, eg. computing the sum of a vector v: 

  sum_v = accumulate(function(acc,value) acc+value,v)
and the maximum: 
  max_v = accumulate(function(acc,value) if (value > acc,value,acc),v)

All of that stuff saves you from writing explicit loops, so it's really compact and quite useful for expressing operations over image regions. It's even better if you can chain operations together to avoid intermediate variables: for example, to compute the mean value below a threshold

 cmean = filter(function(a) a < 4,v).mean

Thinking about it though, in the case of CImg's DSL, it may be hard to implement if vectors are fixed-size and functions are macros.

**Comment by dtschump** [comment]
* Precompilation : yes, it is actually possible (but a bit hacky) to keep the same expression and run it for multiple images. You have to play directly with the `_cimg_math_parser` class, in this case. 

* The specific language defined in `_cimg_math_parser` has been done a bit with the concept of _Shaders_ in mind : it's a kind of primitive language, limited in functionalities, *but* fast to compile and to execute.

That's why I didn't worry too much about being forced to recompile an expression if I want to apply it on another image. The compilation time into bytecode is far from being the bottleneck in the whole expression evaluation process.
That's why also the expression compiler relies on static array for vectors. It has no complex dynamic memory allocation/deallocations to manage, and even better, if the size of the vector is small enough, the compiler is able to unroll the necessary loops (e.g. in `cos([0,1,2])` which computes the cosine of all three vector components).

To explore more how the compiler work, there are two nice functions to know, that are `debug(expression)` and `debugm()` that gives real-time information about the bytecode execution and the memory management.
