### ISSUE TITLE
image rotation introduces significant blurring

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#82]
An imager user is unhappy with the blurring introduced by image rotation [https://github.com/dahtah/imager/issues/17](OP). I've checked and it's true that rotating an image by 360° in ten 36° increments introduces significant blurring, even with cubic interpolation. I know very little about this, any tips on how to get better results?

**Comment by dtschump** [comment]
Not sure what version of CImg you use, but I've slightly improved the rounding error in the rotation method recently, so maybe you could check that first.
Anyway, there is no chances you can get a perfectly sharp result if you iterate the rotation with small angles, due to the rounding error of the interpolation introduced step by step.
I know there is one paper discussing about this particular issue : https://www.gipsa-lab.grenoble-inp.fr/~laurent.condat/publis/condat_icip08_rotations.pdf
It uses some smart filtering techniques, and I've not implemented it yet.

**Comment by dahtah** [comment]
Thanks David, looks like I'm shipping the old version of rotate, I'll have to update. I had a look at Laurent's paper: the approach is neat, but from a purely visual standpoint it looks like the best results are obtained by spline interpolation, don't you agree? The successive shear approach seems to introduce noise instead of blurring.

**Comment by dtschump** [comment]
"Best results" is probably application dependent so I wouldn't give an advice about what type of interpolation to use, but yes spline looks nice enough to me.
