### ISSUE TITLE
mathematical morphology: erosion and dilation with an empty mask

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#95]
Dear David 

erosion and dilation with an empty mask give unexpected results: 

```
#include <CImg.h>
#include <iostream>
using namespace cimg_library;

int main()
{
  CImg<double> im(10,10),out(im);
  CImg<double> msk(3,3);
  im.fill(1);
  msk.fill(0);
  out = im.get_erode(msk);
  std::cout << "Min: " <<out.min() << std::endl; 
  out = im.get_dilate(msk);
  std::cout << "Min: " <<out.min() << std::endl;
  return 1;
}
```

Depending on which definition of erosion and dilation we go for, the output could be 0 or undefined or the original image, but probably not the current output. 
Also, the implementation uses a convolution convention for the mask, instead of a filtering convention. It's a bit counter-intuitive, I suppose it's too late to change things, but maybe it should be documented, or maybe an option to follow the filtering convention should be added?

**Comment by dtschump** [comment]
Dear Simon,
You are right, when the mask has only zero values, the result is not correct. I'm still not sure what could be a correct result though, I need to think about it a little more.
About the 'convolution' convention: It is intuitive in the sense that e.g. when you dilate an image with a single point, with a non symmetrical mask, then you get exactly the mask solution, as shown in the image below (left : image 100x100, middle : mask 20x20, right : result of the dilation).

![dilate](https://cloud.githubusercontent.com/assets/10114565/19036695/c0a60858-8971-11e6-828b-7ece5d1c96d5.png)

**Comment by dtschump** [comment]
Another thought on this : 
According to wikipedia pages https://en.wikipedia.org/wiki/Erosion_(morphology) and https://en.wikipedia.org/wiki/Dilation_(morphology), we can see binary erosion and dilation respectively as intersection and unions with binary sets defined by the mask.
It seems then, it makes sense than when the mask has empty values (`false` everywhere), the result of the erosion should be zero everywhere, and the result of the dilation should be the same as the input image.
I'll add some tests to fix these methods like this, if you agree with the idea.

**Comment by dahtah** [comment]
I agree with you, but the two definitions (set vs. grayscale) clash 
here: the grayscale definition would suggest returning the original 
image in both cases. It's annoying.
The set viewpoint also suggests using the filtering convention, I think 
(it's strange that you'd have to flip your structuring element before 
you can apply it). On the other hand, the Wikipedia definition for 
grayscale goes with the convolution convention.
I'm not sure what other software do.

**Comment by dtschump** [comment]
What I think is probably most people use dilation and erosion with symmetrical kernel, and the question about the filtering/convolution conventions does not arise :)
I personally prefer the convolution convention, because when I apply a non-symmetrical kernel, I _see_ clearly its shape in the "right" natural order in the image. It's the same with a convolution.
I think it's quite intuitive like this.

Also concerning the grayscale versions of erosion/dilation, I don't agree.
If you erode with a 10x10 mask having only zeros, you'll end with something as:

erode(I,M) = inf_(m\in M) [f(x + m) - 0] 

with does not return I, but which is equivalent to the binary erosion with a 10x10 kernel set to 1 everywhere.

**Comment by dahtah** [comment]
You're right about the grayscale version

**Comment by aalbiol** [comment]
This thread in my opinion has two main aspects:
 - non symmetric masks
 - masks (called structuring elements in morphological terminology) with all elements equal to zero.

With respect to non-symmetric masks, dilation should be implemented as a convolution with the mask while erosion as a correlation.  The reason for this is that when you compute an open (erosion followed by dilation with the same mask) this operation must be idempotent. In other words, computing twice the open with the same structuring element yields the same result as doing it once.
In Jean Serra's page there is a course where this is explained clearly.
http://cmm.ensmp.fr/~serra/cours/pdf/fr/ch2fr.pdf 
In slide 16 have a look at the erosion definition "**-**b belongs to B"
Perhaps the most typical application of non-symmetric structuring elements is when doing erosions/dilations with bi-points, one at the center of the structuring element.

**Comment by aalbiol** [comment]
With respect to masks, the most common type of structuring elements are "flat" structuring elements. In that case, only the shape of the mask is important, and the erosion is computed as the minimum value of pixels that fall under the translated mask. This kind of mask can be represented by a boolean matrix, normally setting to ones pixels that belong to the mask. I think that this is the implementation in CImg.

However flat structuring elements are a particular case of non-flat ones.
An explanation can be found in slides 18-19 of 
http://cmm.ensmp.fr/~serra/cours/pdf/fr/ch2fr.pdf
A non-float structuring element can be represented as a matrix of floating point numbers.Since the matrix must have a finite extent elements outside the matrix containing the structuring element should be considered as -infinity.
In order to represent a flat structuring element using a floating point matrix, the true elements in the boolean mask must be set to zero in the floating point matrix while the false values in the boolean mask must be set to -infinity in the floating point mask.
In that context, a floating point mask with elements to zero, in my opinion should do the same as a boolean mask with all elements set to true.

By the way, dilation with a rectangular mask can be computed much faster with the method .dilate(int,int) in CImg Library!

In my opinion non-flat structuring elements are very rarely used. They have a much greater computational cost and I don't know any application that may require that.
Flat structuring elements with arbitrary shape are also very rarely used because of the computational cost.
For instance, to make dilations with big circles, it is possible to approximate  them by dilations with octogons, which in turn can be very effienctly decomposed as dilations with squares and linear diagonal structuring elements. Dilations with squares and linear structuring elements can be computed recursively very efficiently. In fact, dilation by a horizontal line of ANY size can be computed with an average of three comparisons per pixel (see CImg function that receives ints as args)

**Comment by dtschump** [comment]
Dear Antonio, thanks for these insights. That makes sense.
Thus, I think I need to 'revert' the order for the erosion operator, to have make it follow the 'correlation' convention.
Note that in CImg, there is a boolean argument `is_real` that can be enabled to compute non-flat dilation/erosion. If 'is_real' is set and the mask contains only zero, then the dilation/erosion indeeds do the equivalent operation to binary mask set to 1 everywhere, which is correct.

So, I think the only 'bug' remaining is the correlation order that must be used in the erosion operator.
I'll fix that ASAP.

Many thanks for your useful comments !

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/CImg/commit/b52944c8a11d25e67d9d2a476fd6b050963d5759 should make things better.

**Comment by dtschump** [comment]
Now I have a real problem with the following question : Where should be considered to be the "center" of a mask when the size is even ?
Does it have to depend on the process ? For instance, if we have a 2x2 dilation, followed by a 2x2 erosion, it should return the original image (if the original image is a set of distinct points for instance). But this means the center for the dilation mask and erosion mask must be located in different places (a bit on the upper-left for the dilation, a bit on the lower-right for the erosion).
What do you think ?
The same question arises for convolution / correlation, and median filtering for instance.
I'm a bit lost, I have no clear answers at this point.

**Comment by devernay** [comment]
I think that when using a mask, the user should provide the center (with integer coordinates).
Strange masks seem to be used a lot in granullometry, and sometimes they are not centered in any way. A mask may have an even size, with a clearly identifed center.

BTW, I looked at it recently, and it would be nice to implement:
- erode/dilate with a periodic line structuring element (optimized of course, not via a mask)
- an optimized "disk" structuring element implemented as a decomposition in periodic lines.
Refs are at the bottom of https://fr.mathworks.com/help/images/ref/strel-class.html

Also, erode/dilate with a non-binary mask would be great.
I saw two versions of the non-binary mask:
- a version where the values are added to the mask before taking the max (classical definition)
- a version where the values are mutiplied by the mask before taking the max (which doesn't require to know the value range in advance and to adjust the mask range)
Areas outside of the non-binary mask are simply set to 0 in the first case, or -infinity in the second case.

**Comment by dtschump** [comment]
After a night of thinking about this, here is what I've done so far, for masks NxN with N being even.
- `CImg<T>::dilate()` and `CImg<T>::convolve()` are centered such that their impulse response (e.g. when they are applied on an image with a single point) renders the mask shape centered at `(N/2-1,N/2-1)`.
- On the contrary, `CImg<T>::erode()` and `CImg<T>::correlate()` have impulse responses centered on `(N/2+1,N/2+1)`.

This way, dilation and erosion stay inverse operations for even masks. And that means that correlation gives a measure of the similarity between patches that can be considered centered at `(N/2-1,N/2-1)` too, which is the 'natural' centering used in all other CImg functions that are considering patches
(patch size always grows first in the forward direction, the in the backward direction, see e.g. the `cimg_forNxN` loop macros, used everywhere in CImg). I've modified the `CImg<T>::blur_median()` function as well to follow this rule.

I'm not sure having additional parameters to specify the kernel center is really necessary. People can just add `0` to their mask if they want a specific centering (or write their own small loop if they have such very specific needs).

**Comment by aalbiol** [comment]
David,
you are right.
For even sized masks, the center must be located in slightly different
locations for erosion and dilation:

center_erosion = floor( (size-1) / 2);
center_dilation = ceil( (size-1) / 2 );

for convolution/correlation masks with even size cause a displacement of
half_pixel. In my opinion it is irrelevant if you round with floor or ceil.
Only if the same convolution had to be iterated a certain number of times,
the displacement should be made in alternating directions so that half
pixel displacements don't acumulate.

For median filters it's the same as for convolution-correlation.

Just to get ideas from other libraries in opencv, erosion and dilation have
an argument called "anchor_point" that is used for specifying the mask
center
http://docs.opencv.org/3.0-beta/modules/imgproc/doc/filtering.html#erode

I think opencv is a bit excesive and not necessary at all. Changing erosion
and dilation with the above criteria, should be enough for most
applications. In fact, when I sent you the code for recursive
implementation of erosion and dilation, that half pixel shift was also
taken into account!

Regards and congratulations for the library.! I use it with my students
every year with great success!

Antonio

On Thu, Oct 20, 2016 at 6:28 PM, David Tschumperlé <notifications@github.com
